version: '3.8'
services:
  crawl4ai:
    image: unclecode/crawl4ai:all-amd64
    platform: linux/amd64
    ports:
      - "11235:11235"
    environment:
      - CRAWL4AI_API_TOKEN=crawl4a-local-key  # Optional API security
      - MAX_CONCURRENT_TASKS=5
      # LLM Provider Keys
      # - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      # - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
    volumes:
      - /dev/shm:/dev/shm
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G

  qdrant-vector-db:
    image: qdrant/qdrant
    container_name: qdrant-vector-db
    ports:
      - "6333:6333"  # Qdrant API port
      - "6334:6334"  # Qdrant web UI port
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
